#!/usr/bin/env python3
"""Keep per-skill reference files in sync with their single sources of truth.

Every skill directory must stay self-contained (users may copy one skill
folder), so some references are duplicated:

- SHARED: a canonical hand-written file inside one skill, copied verbatim into
  other skills (only the leading HTML comment header differs);
- GENERATED: files rendered from vocab/*.yaml and rules/registry.yaml
  (plus rules/support.json when present).

    python scripts/build_refs.py --check   # exit 1 if anything is stale (CI)
    python scripts/build_refs.py --write   # regenerate / re-copy
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pa_lib.common import REGISTRY, SUPPORT, VOCAB_DEFECTS, VOCAB_MOVES, load_registry, load_yaml  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
SKILLS = REPO / "skills"

SHARED: dict[str, list[str]] = {
    "pa-section-writer/references/evidence-discipline.md": [
        "pa-intro-drafter/references/evidence-discipline.md",
        "pa-literature-mapper/references/evidence-discipline.md",
        "pa-paper-reviewer/references/evidence-discipline.md",
        "pa-revision-responder/references/evidence-discipline.md",
        "pa-title-abstract/references/evidence-discipline.md",
        "pa-prose-polisher/references/evidence-discipline.md",
    ],
    "pa-prose-polisher/references/prose-guardrails.md": [
        "pa-intro-drafter/references/prose-guardrails.md",
        "pa-section-writer/references/prose-guardrails.md",
        "pa-title-abstract/references/prose-guardrails.md",
        "pa-revision-responder/references/prose-guardrails.md",
    ],
    "pa-question-framer/references/argument-chain.md": [
        "pa-router/references/argument-chain.md",
        "pa-intro-drafter/references/argument-chain.md",
        "pa-paper-reviewer/references/argument-chain.md",
    ],
    "pa-argument-architect/references/nested-argument.md": [
        "pa-paper-architect/references/nested-argument.md",
    ],
}


def _strip_header(text: str) -> str:
    s = text.lstrip()
    if s.startswith("<!--"):
        end = s.find("-->")
        if end != -1:
            return s[end + 3:].lstrip("\n")
    return text


def _gen_header(source: str) -> str:
    return f"<!-- GENERATED by scripts/build_refs.py from {source}; do not edit by hand. -->\n"


def render_defects() -> str:
    d = load_yaml(VOCAB_DEFECTS)
    out = [_gen_header("vocab/defects.yaml"), f"# 稿件缺陷编码（v{d['version']}）", "",
           "诊断时统一使用以下编码。severity 为默认严重度：fatal 不修就不成立，major 明显影响发表，minor 影响质量但不致命；可按稿件调整，但要说明理由。", "",
           "## 目录", ""]
    out += [f"- {g} {name}" for g, name in d["groups"].items()]
    for g, name in d["groups"].items():
        out += ["", f"## {g} {name}", "", "| 编码 | 名称 | 默认严重度 | 症状 | 检验 | 修复 | 转交 |", "|---|---|---|---|---|---|---|"]
        for x in d["defects"]:
            if x["group"] == g:
                out.append(f"| {x['code']} | {x['label']} | {x['severity']} | {x['symptom']} | {x['test']} | {x['fix']} | `{x['route']}` |")
    return "\n".join(out) + "\n"


def render_codebook() -> str:
    m = load_yaml(VOCAB_MOVES)
    out = [_gen_header("vocab/research-moves.yaml"), f"# 研究动作编码本（codebook {m['version']}）", "",
           "只在论文里能找到原文证据时才打码；一篇论文每族通常 1–4 个码。示例均为虚构，不对应任何真实论文。", "",
           "## 目录", ""]
    out += [f"- {f} {meta['label']}" for f, meta in m["families"].items()]
    for fam, meta in m["families"].items():
        out += ["", f"## {fam} {meta['label']}", "", f"判断问题：{meta['question']}", "",
                "| 编码 | 名称 | 定义 | 纳入 | 排除 | 示例 |", "|---|---|---|---|---|---|"]
        for x in m["moves"]:
            if x["family"] == fam:
                out.append(f"| `{x['code']}` | {x['label']} | {x['definition']} | {x['include']} | {x['exclude']} | {x['example']} |")
    return "\n".join(out) + "\n"


def _lens_cards(statuses: list[str], preview: bool) -> str:
    reg = load_registry(REGISTRY)
    support = {}
    if SUPPORT.exists():
        support = json.loads(SUPPORT.read_text(encoding="utf-8")).get("rules", {})
    legend = "；".join(f"`{k}` {v.rstrip('。')}" for k, v in reg["statuses"].items())
    shown = "、".join(statuses)
    if preview:
        out = ["<!-- GENERATED by scripts/build_refs.py from rules/registry.yaml; research preview, NOT loaded by any skill. -->",
               "# 研究镜头卡（研究区预览）", "",
               f"本文件列出状态为 {shown} 的全部规则及其来源传统，供标注与验证使用。**不被任何 Skill 加载**；"
               "Skill 只加载 `rules/registry.yaml` 中 `build.runtime_statuses` 指定状态的规则。", "",
               "来源传统一栏只说明规则从哪个公开研究传统中抽象而来，不代表相关学者认可，也不是对其观点的概括。", ""]
    else:
        out = [_gen_header("rules/registry.yaml").rstrip("\n"), "# 研究镜头卡", "",
               "镜头只是研究动作的抽象，不代表任何学者的观点，不得用来扮演具体学者。", "",
               f"本文件只加载状态为 {shown} 的规则；镜头的「关注」「追问」「输出」「常见失败」是启发式检查，不是经过验证的规则。"
               "尚在验证中的规则不在此处出现。", ""]
    out += [f"规则状态：{legend}", "", "## 目录", ""]
    lenses = [l for l in reg["lenses"] if l["id"] == "SH"] + [l for l in reg["lenses"] if l.get("panel")]
    out += [f"- {l['id']} {l['name']}" for l in lenses]
    for lens in lenses:
        out += ["", f"## {lens['id']} {lens['name']}", ""]
        if preview and lens["tradition"]["scholars"]:
            out += [f"**来源传统**：{'、'.join(lens['tradition']['scholars'])}（{lens['tradition']['note']}）", ""]
        if lens.get("focus"):
            out.append(f"**关注**：{lens['focus']}")
        if lens.get("questions"):
            out += ["", "**追问**：", ""] + [f"- {q}" for q in lens["questions"]]
        if lens.get("output"):
            out += ["", f"**输出**：{lens['output']}"]
        if lens.get("typical_failure"):
            out += ["", f"**常见失败**：{lens['typical_failure']}"]
        all_rules = [r for r in reg["rules"] if r["lens"] == lens["id"] and r["status"] != "rejected"]
        rules = [r for r in all_rules if r["status"] in statuses]
        if rules:
            out += ["", "**规则**：", ""]
            for r in rules:
                sup = support.get(r["id"])
                tag = f"{r['status']}" + (f"，训练集支持 {sup['n_support']} 篇" if sup else "")
                out.append(f"- **{r['id']}**（{tag}）当{r['trigger'].rstrip('。')}时：{r['action']} 检验：{r['check']} 反模式：{r['anti_pattern']}")
        elif not preview:
            pending = len(all_rules)
            out += ["", f"本镜头暂无已验证规则（另有 {pending} 条规则在验证中，未加载）。"]
    return "\n".join(out) + "\n"


def render_lens_cards() -> str:
    reg = load_registry(REGISTRY)
    return _lens_cards(list(reg.get("build", {}).get("runtime_statuses", ["validated"])), preview=False)


def render_lens_preview() -> str:
    reg = load_registry(REGISTRY)
    return _lens_cards(list(reg.get("build", {}).get("preview_statuses", ["seed", "candidate", "validated"])), preview=True)


GENERATED = {
    "pa-paper-reviewer/references/defect-codes.md": render_defects,
    "pa-supervisor-panel/references/defect-codes.md": render_defects,
    "pa-revision-responder/references/defect-codes.md": render_defects,
    "pa-scholar-distiller/references/defect-codes.md": render_defects,
    "pa-scholar-distiller/references/move-codebook.md": render_codebook,
    "pa-supervisor-panel/references/lens-cards.md": render_lens_cards,
}


def expected_files() -> dict[Path, str]:
    files: dict[Path, str] = {}
    for canonical, copies in SHARED.items():
        cpath = SKILLS / canonical
        if not cpath.exists():
            raise SystemExit(f"build_refs: canonical missing: skills/{canonical}")
        body = _strip_header(cpath.read_text(encoding="utf-8"))
        files[cpath] = (f"<!-- CANONICAL shared reference. Copies: {', '.join(c.split('/')[0] for c in copies)}. "
                        f"Edit here, then run scripts/build_refs.py --write. -->\n" + body)
        for c in copies:
            files[SKILLS / c] = f"<!-- COPY of skills/{canonical}; edit the canonical file and run scripts/build_refs.py --write. -->\n" + body
    for rel, fn in GENERATED.items():
        files[SKILLS / rel] = fn()
    files[REPO / "rules" / "preview" / "lens-cards-preview.md"] = render_lens_preview()
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true")
    g.add_argument("--write", action="store_true")
    args = ap.parse_args()
    stale = []
    for path, content in expected_files().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
            if args.write:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    rel = [str(p.relative_to(REPO)) for p in stale]
    if args.check:
        if stale:
            print(f"build_refs: {len(stale)} stale file(s):")
            for r in rel:
                print(f"  {r}")
            print("run: python scripts/build_refs.py --write")
            return 1
        print(f"build_refs: {len(expected_files())} shared/generated file(s) in sync")
        return 0
    print(f"build_refs: wrote {len(stale)} file(s)" + ("".join(f"\n  {r}" for r in rel) if rel else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
